eclipse/microprofile-reactive-messaging

- pom.xml
- tck/pom.xml
The version has been stripped out during the move.
> Add the microprofile-maven-build-extension version

- api/src/main/java/org/eclipse/microprofile/reactive/messaging/Incoming.java
- api/src/main/java/org/eclipse/microprofile/reactive/messaging/Outgoing.java
- api/src/main/java/org/eclipse/microprofile/reactive/messaging/package-info.java
- tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/CompletionStageIncomingMethodVerification.java
Related to #8
Just renamed the `@Incoming` and `@Outgoing` `topic` attribute to `name`.
> Rename the `topic` attribute to `name`

- spec/src/main/asciidoc/architecture.asciidoc
> Add signatures, scope and acknowledgement sections to the spec

- core-tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/signatures/subscribers/SubscriberBean.java
- spec/src/main/asciidoc/architecture.asciidoc
Write the connector section in the spec.
Related to #22.
> Add connector section to the specification document

- spec/src/main/asciidoc/architecture.asciidoc
- spec/src/main/asciidoc/rationale.asciidoc
As discussed in today's hangout.
> Improve spec for duplicate channels

- api/src/main/java/org/eclipse/microprofile/reactive/messaging/spi/IncomingConnectorFactory.java
- api/src/main/java/org/eclipse/microprofile/reactive/messaging/spi/OutgoingConnectorFactory.java
Signed-off-by: Gordon Hutchison <Gordon.Hutchison@gmail.com>
> Add in connector attributes to the ConnectorFactory javadoc

- core-tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/connector/ConnectorTest.java
- core-tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/connector/DummyConnector.java
- core-tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/connector/FakeConfig.java
As discussed during the hangout, here are a few tests around the new format.
> Add test to the TCK checking the new connector config format.

- spec/src/main/asciidoc/architecture.asciidoc
* Use `NOTE:` instead of `INFO:`
* Replace "flatten" with "flattened"
> Small spec fixes

- api/src/main/java/org/eclipse/microprofile/reactive/messaging/spi/IncomingConnectorFactory.java
- api/src/main/java/org/eclipse/microprofile/reactive/messaging/spi/OutgoingConnectorFactory.java
- tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/connector/DummyConnector.java
> Remove use of raw Message type

- api/pom.xml
- api/src/main/java/org/eclipse/microprofile/reactive/messaging/package-info.java
- spec/src/main/asciidoc/architecture.asciidoc
> tidy up the spec

- api/pom.xml
- api/src/main/java/org/eclipse/microprofile/reactive/messaging/Acknowledgment.java
- api/src/main/java/org/eclipse/microprofile/reactive/messaging/spi/Connector.java
- api/src/main/java/org/eclipse/microprofile/reactive/messaging/spi/IncomingConnectorFactory.java
- api/src/main/java/org/eclipse/microprofile/reactive/messaging/spi/OutgoingConnectorFactory.java
- api/src/main/java/org/eclipse/microprofile/reactive/messaging/spi/package-info.java
- pom.xml
- spec/src/main/asciidoc/architecture.asciidoc
* Provides a package-info for the SPI package
* Removes outdated content from the `Acknowledgement` class
* Fixes link to DeploymentException in the `OutgoingConnectorFactory`
* Fixes capitalization in the Connector `value` method
> Small improvements in the Javadoc

- api/pom.xml
- pom.xml
- spec/pom.xml
- tck/pom.xml
Few incompatibilities and missing dependencies have been caught while trying to build it with Java 11. With this PR, it works with both Java 8 and Java 11.
> Make the build works with Java 8, and Java 11

- pom.xml
It update the reactive streams version to 1.0.3.
> Fix #65 - Update the MicroProfile Reactive Streams version to 1.0.1

- tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/invalid/InvalidConfigurationTest.java
Fix https://github.com/eclipse/microprofile-reactive-messaging/issues/76
> Fix incorrect bean name, issue #76

- api/pom.xml
- api/src/main/java/org/eclipse/microprofile/reactive/messaging/spi/package-info.java
> #73 set up baseline for versioning

- pom.xml
- spec/src/main/asciidoc/architecture.asciidoc
- tck/pom.xml
- tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/metrics/ConfigAsset.java
- tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/metrics/MetricsTest.java
- tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/metrics/MetricsTestBean.java
- tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/metrics/TestConnector.java
Part of #31 
Add spec and tests a metric for the number of messages sent through a channel.
> Spec and TCK for message count metrics

- tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/metrics/MetricsTestBean.java
* Change volatile int to an AtomicInteger
* Remove debug println
Fixes #91
> Fixes to the MetricsTestBean

- api/src/main/java/org/eclipse/microprofile/reactive/messaging/Outgoing.java
> #99 fix Outgoing javadoc

- spec/src/main/asciidoc/architecture.asciidoc
Signed-off-by: Daniel Kec <daniel.kec@oracle.com>
> Spec typos

- .github/ISSUE_TEMPLATE/01-compatible-certification-request.md
- .github/workflows/build.yml
- api/pom.xml
- api/src/main/javadoc/licenses/Draft/license.html
- api/src/main/javadoc/licenses/Final/license.html
- pom.xml
- spec/pom.xml
- spec/src/main/asciidoc/license-efsl.adoc
- spec/src/main/asciidoc/microprofile-reactive-messaging-spec.asciidoc
- tck/pom.xml
- tck/src/main/licenses/Draft/LICENSE
- tck/src/main/licenses/Final/LICENSE
Ideally, this should use the new Parent POM, to avoid all the duplication, but since we don't have that completely approved, we need to do it the hard way :)
> Prepare MP Reactive Messaging for Release. Add correct Licenses.

- spec/src/main/asciidoc/architecture.asciidoc
Fix wrong code snippet in the specification.
> Fix wrong Emitter parameter in spec

- api/src/main/java/org/eclipse/microprofile/reactive/messaging/Acknowledgment.java
> Extend @Acknowledgement javadoc to list the supported strategies and the default one for each signature

- api/src/main/java/org/eclipse/microprofile/reactive/messaging/spi/ConnectorAttribute.java
- api/src/main/java/org/eclipse/microprofile/reactive/messaging/spi/ConnectorAttributes.java
- spec/src/main/asciidoc/architecture.asciidoc
Defines the @ConnectorAttribute and @ConnectorAttributes annotations
> Add @ConnectorAttribute

- spec/src/main/asciidoc/microprofile-reactive-messaging-spec.asciidoc
- spec/src/main/asciidoc/release_notes.asciidoc
> Prepare release notes for the 2.0 release

- api/pom.xml
- pom.xml
- spec/pom.xml
- tck/pom.xml
> update versions for release

- pom.xml
> fix gpg issue

- pom.xml
> use the final release of reactive streams operators

- .github/ISSUE_TEMPLATE/01-compatible-certification-request.md
> correct issue template

- tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/EmitterInjectionMessageBeanWithPayloadsWithAckTest.java
The archive is missing a class needed by the test
> Deployment missing MyMessageBean

- spec/src/main/asciidoc/release_notes.asciidoc
> Add release notes for the 3.0 release

- tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/overflow/ThrowExceptionOverflowStrategyOverflowTest.java
Fixes #145
Signed-off-by: Daniel Kec <daniel.kec@oracle.com>
> Wrong assertion, test data starts with 0 #145
