api/src/main/java/org/eclipse/microprofile/reactive/messaging/Acknowledgment.java

Propose the `Acknowledgement` annotation.
It results of the discussions that happened on https://docs.google.com/spreadsheets/d/11cNwX8eXKTKjoF_amXTPLU1-DfrYxwu4VLnEideBy7Q/edit#gid=0
Open questions: 
* Should the implementation use a default acknowledgment strategy when the annotation is not used
* Should the implementation throw a `DeploymentException` when a non-supported acknowledgment strategy is used
* Should `MANUAL` and `NONE` be merged?

Define the Acknowledgement annotation

---

core-tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/scope/DependantBeans.java
core-tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/signatures/publishers/VerifierForPublisherBean.java
core-tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/signatures/subscribers/SubscriberBean.java

The current TCK didn't check the method returning `SubscriberBuilder` instances. 
This PR adds the missing tests.
Also, it fixes 2 concurrency issues in the Publisher tests and Dependant scope test.

Extend TCK with SubscriberBuilder

---

api/src/main/java/org/eclipse/microprofile/reactive/messaging/spi/ConnectorLiteral.java
core-tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/connector/ConnectorTest.java
core-tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/scope/DependantBeans.java
core-tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/scope/DependantScopeTest.java

This PR:
* Fixes the TCK after the `@Connector` integration
* Adds a `ConnectorLiteral`, not because it's complicated, but because all implementations would need one. (discussed during the hangout, and forgot about it)
* Re-implements the DependantScope test as it was very brittle

Fix TCK after the integration of the @Connector qualifier

---

spec/src/main/asciidoc/architecture.asciidoc

Fix #29.
This PR is the result of our discussions around acknowledgment:
* Forbid the usage of `POST_PROCESSING` when dealing with `Messages` - the user is responsible for the acknowledgment in this case.
* Clarify when the acknowledgment happens and how the chain of ack works
* Add more examples
* Fix a few typos

Clarify the acknowledgement mechanism

---

spec/src/main/asciidoc/architecture.asciidoc

If the user's processor produces the message, the reactive messaging
implementation cannot determine when that message is acknowledged
without wrapping it and hiding the actual class of the Message.
I think this was missing from #44

Forbid post-processing ack where a Processor produces a Message

---

api/pom.xml

Following the discussion on https://github.com/eclipse/microprofile/issues/56, this commit changes the scope of the CDI dependency to `provided` and excludes explicitly the dependency on EL

Declare the CDI dependency in the `provided` scope and exclude EL

---

tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/scope/ApplicationBeans.java

Move the initialization of the the id field in ApplicationBeans from the
constructor to a PostConstruct method.
The test that uses this class verifies that only one instance of the
ApplicationScoped bean is created.
However, because this is a normal scoped bean, the container may need to
create client proxies for this class and when it constructs one of
these, it will call the zero-arg constructor.
Therefore, although only one instance of the bean will be created, its
constructor may be called more than once.
Setting up the id in a PostConstruct method avoids this issue because
the PostConstruct method won't be called when creating a client proxy.

Fix the ApplicationScopedTest

---

api/src/main/java/org/eclipse/microprofile/reactive/messaging/Message.java

This would allow users of a connector to avoid casting. Instead, the user would use the `unwrap` method. For instance: `KafkaMessage myMessage = msg.unwrap(KafkaMessage.class)`.
The default implementation only supports `Message` as parameter. Connector implementation would need to override the method.

Add an unwrap method to the Message interface.

---

tck/pom.xml

Was mostly done everywhere except in the TCK.

Fix #62 - Exclude the EL transitive dependency from CDI

---

api/bnd.bnd

Resolves #69
The OSGi metadata for the api artifact imports a nonexistent package,
making it difficult to deploy this bundle in an OSGi runtime. This
commit removes the explicit import of that package, relying instead on
the dynamic bnd import mechanism.

OSGi: remove non-existent microprofile.reactive.streams import

---

spec/src/main/asciidoc/architecture.asciidoc
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/signatures/invalid/IncomingReturningNonVoid.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/signatures/invalid/IncomingReturningNonVoidCompletionStage.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/signatures/invalid/InvalidSubscriberSignatureTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/signatures/subscribers/SubscriberBean.java

Fix #79
* Remove tests using non-supported signatures
* Add new tests in the TCK to be sure these non-supported signatures are detected and reported using CDI Definition Exception
* Clarify the spec about these signatures

Clarify @Incoming method signatures

---

spec/src/main/asciidoc/architecture.asciidoc

The spec was missing the second generic parameter when mentioning SubscriberBuilder. This commit fixes this and adds `Void`.

Missing second parameter for SubscriberBuilder in spec

---

api/src/main/java/org/eclipse/microprofile/reactive/messaging/Acknowledgment.java
spec/src/main/asciidoc/architecture.asciidoc

When consuming/producing Messages, the default acknowledgment should be MANUAL instead of PRE_PROCESSING.
When using messages, you should have full control. You can still set the strategy to `PRE` or `POST`. It was creating a non-homogeneous experience. So, with this change, the experience is homogeneous.

Update default ack strategy when dealing with Message

---

tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/signatures/publishers/VerifierForPublisherBean.java

Relax a check which was ensuring that publishers stopped being called
immediately when they were cancelled. The reactive streams spec says
that a publisher must stop producing messages eventually when cancelled,
but doesn't require it to stop immediately.
Fixes #95

Relax check that publisher stops when cancelled

---

spec/src/main/asciidoc/architecture.asciidoc
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/metrics/MetricsTest.java

Specify the scope in the spec and update TCK to expect metrics in the `BASE` scope
Fixes #93

Move metrics to the base scope

---

api/src/main/java/org/eclipse/microprofile/reactive/messaging/Channel.java
spec/src/main/asciidoc/architecture.asciidoc
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/BeanInjectedWithDifferentFlavorsOfTheSameChannel.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/BeanWithMissingChannel.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/ChannelInjectionDifferentFlavourSameChannelTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/EmitterInjectionMissingChannelTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/connector/ConnectorTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/invalid/BeanConsumingManyTwice.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/invalid/BeanProducingManyTwice.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/invalid/ChannelMissingUpstream.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/invalid/ChannelMultipleUpstreams.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/invalid/EmitterMissingDownstream.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/invalid/EmitterMultipleDownstreams.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/invalid/InvalidConfigurationTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/invalid/ProcessorMissingDownstream.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/invalid/ProcessorMissingUpstream.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/invalid/ProcessorMultipleDownstreams.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/invalid/ProcessorMultipleUpstreams.java

Implementation must check the validity of the graph at startup time. 
This PR:
* add a section in the spec about that
* add TCK tests verifying that the implementation validates the graph
Because of that, the BeanMissingChannel test should fail at startup as there is no `downstream` channel for the emitter. It's a definition exception (equivalent to injecting a missing bean).
The ChannelInjectionDifferentFlavourSameChannelTest is invalid as a single upstream cannot, by default, emit values to multiple (6 in the case of the tests) downstream. Implementations could support such behavior, but the TCK should not assume that this mechanism exists or is the default behavior. This is now checked by the TCK

Assembly validation

---

api/src/main/java/org/eclipse/microprofile/reactive/messaging/Emitter.java
api/src/main/java/org/eclipse/microprofile/reactive/messaging/Message.java
pom.xml
spec/src/main/asciidoc/architecture.asciidoc
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/AsynchronousMessageProcessorAckTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/AsynchronousMessageSubscriberAckTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/AsynchronousPayloadProcessorAckTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/AsynchronousPayloadSubscriberAckTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/EmitterBean.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/EmitterOfMessageAcknowledgementTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/EmitterOfPayloadAcknowledgementTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/MessageProcessorAckTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/PayloadProcessorAckTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/PayloadSubscriberAckTest.java

Add support for negative acknowledgement
* Add `nack` method to the `Message` interface
* Explain `ack` / `nack` on the `Emitter` javadoc
* Extend specification to cover negative acknowledgement
* Extend TCK to verify acknowledgement and negative-acknowledgement

Negative Acknowledgement

---

api/pom.xml
pom.xml
tck/pom.xml

* Change EE, MP and OSGi dependencies to `provided` scope
* Be consistent with where we set scope and version (scope in the child pom, versions in the parent pom)
* Update to Jakarta EE 8 APIs
Fixes #75
Fixes #88
Fixes #89
This may require changes to user's builds as previously including the Reactive Messaging API would pull in the MP Config and MP Reactive Streams Operators APIs as transitive dependencies but now it won't.

Dependency fixes

---

tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/BeanInjectedWithAPublisherBuilderOfMessages.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/BeanInjectedWithAPublisherBuilderOfPayloads.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/BeanInjectedWithAPublisherOfMessages.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/BeanInjectedWithAPublisherOfPayloads.java

This is to make them proxyable according to the CDI specification.

Add default constructors to beans using constructor injection

---

tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/overflow/DefaultOverflowStrategyOverflowTest.java

Default strategy shouldn't emit onError signal to the downstream

---

.github/workflows/build.yml
pom.xml
tck/pom.xml

Brings in the latest versions of our build and test dependencies.
Required to build on the latest version of Maven

Update to MicroProfile Parent 2.8

---

tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/AsynchronousMessageProcessorAckTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/AsynchronousMessageSubscriberAckTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/AsynchronousPayloadProcessorAckTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/AsynchronousPayloadSubscriberAckTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/EmitterOfMessageAcknowledgementTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/EmitterOfPayloadAcknowledgementTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/MessageProcessorAckTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/PayloadProcessorAckTest.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/PayloadSubscriberAckTest.java

During running of the 3.0 TCK. It was found that for a number of the newer test classes that extended TckBase, did not include the TckBase class in the application archive would throw ClassNotFoundException TckBase when run on Open Liberty.
Use the `getBaseArchive()` to include base classes and configuration and only add the additional classes for those tests.
All the affected tests use the same ServiceLoader and manifest resource as defined in `getBaseArchive()`

Include TckBase.class in application archives where test class extends TckBase

---

tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/overflow/DropOverflowStrategyOverflowTest.java

It is highly unlikely but the list of undropped payloads can contain `"999"`. We know for sure that the number of emitted messages will be less than what is trying to be sent.

Replace flaky assertion on DropOverflowStrategyOverflowTest

---

spec/src/main/asciidoc/architecture.asciidoc

Fixes an error in one of the method signatures and a few grammatical fixes.

Signature error and minor grammar fixes

---

tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/overflow/BeanWithFailOverflowStrategy.java
tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/overflow/FailOverflowStrategyOverflowTest.java

Fail overflow test can fail to pass if exception is thrown after more then 256 messages have been processed.
increase window within which a failure can occur by applying a similar change as was done in https://github.com/eclipse/microprofile-reactive-messaging/pull/158

Make Fail Overflow Test less flaky
